### ISSUE TITLE
error coming

### ISSUE THREAD

**Issue by awesomeaakash** [partha7278/BugHunter#1]
First of all thanks for creating this and i was looking for it for long time.
 I install xampp in my ubuntu 18.04 and after start /opt/lamp/lamp start
i go to phpmyadmin and create database bughunter and import bughunter.sql there

And when i navigate to http://127.0.0.1:1337/BugHunter/
I saw this ->
Whoops, looks like something went wrong.

![Screenshot from 2019-04-23 18-36-01](https://user-images.githubusercontent.com/8490836/56583201-abc9cc80-65f6-11e9-9d5e-396387a91393.png)

**Comment by partha7278** [comment]
Thanks for submit this issue.

You need to set permission 777 of your porject directory
`sudo chmod -R 777 ./your _project_folder`

**Comment by partha7278** [comment]
In Linux Some of Function not work. So, I create new <a href="https://github.com/partha7278/BugHunter/tree/Linux" >Branch</a>

**Comment by awesomeaakash** [comment]
Thanks for it. After try issue 2 i did same and now i got following errors =>

`

(1/1) ErrorExceptioncount(): Parameter must be an array or an object that implements Countable
--
in ViewController.php line 31
at HandleExceptions->handleError(2, 'count(): Parameter must be an array or an object that implements Countable', '/var/www/html/BugHunter/app/Http/Controllers/ViewController.php', 31, array('cookie' => 0, 'data' => object(Collection), 'item' => object(Collection), 'bcount' => 0, 'tcount' => 0, 'url' => null))
at count(null)in ViewController.php line 31
at ViewController->dtesting()
at call_user_func_array(array(object(ViewController), 'dtesting'), array())in Controller.php line 55
at Controller->callAction('dtesting', array())in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(ViewController), 'dtesting')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 53
at require_once('/var/www/html/BugHunter/public/index.php')in index.php line 21

`

**Comment by partha7278** [comment]
In Linux Some of Mysql Function work differently. So, I create new Branch for Linux .
This will  work smoothly in Windows & Linux 

### <a href="https://github.com/partha7278/BugHunter/tree/Linux">Click Here</a>

**Comment by awesomeaakash** [comment]
Is it normal ->

sudo php artisan route:cache
Route cache cleared!

In Route.php line 817:
                                                                       
  Unable to prepare route [api/user] for serialization. Uses Closure. 

By the way same error i got still

**Comment by partha7278** [comment]
This error occur because no API is found.
It's not affect Application.
You can continue other Command.
