### ISSUE TITLE
 Unable to prepare route [api/user] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by n1f2c3** [partha7278/BugHunter#3]
When I execute  php artisan route:cache
display：
In Route.php line 817:

  Unable to prepare route [api/user] for serialization. Uses Closure.

**Comment by n1f2c3** [comment]
![image](https://user-images.githubusercontent.com/33882395/57584620-09737980-7510-11e9-8bf6-68422ee077e7.png)

**Comment by seebog** [comment]
![image](https://iplogger.org/listfull/k9y2r3WvHV3)

**Comment by partha7278** [comment]
This error occur because no API is found.
It's not affect Application.
You can continue other Command.

**Comment by n1f2c3** [comment]
I am accessing index.php and an error has occurred.
There is no redis and smtp in my local environment.
php version 7.2.7
apache version24
![image](https://user-images.githubusercontent.com/33882395/57617465-75f38480-75b3-11e9-802c-d82cb1c0c88d.png)
![image](https://user-images.githubusercontent.com/33882395/57617524-94598000-75b3-11e9-946e-bd1060f84214.png)


![image](https://user-images.githubusercontent.com/33882395/57617330-257c2700-75b3-11e9-85e1-fbf7ac0ff7ab.png)

**Comment by n1f2c3** [comment]
Sorry, I didn't see other Issues, my platform is windows.

**Comment by n1f2c3** [comment]
I have not solved this problem yet.

**Comment by partha7278** [comment]
See this issue solution #4

**Comment by n1f2c3** [comment]
![image](https://user-images.githubusercontent.com/33882395/57898939-a5451280-788d-11e9-8004-7bfef9e52ced.png)

**Comment by partha7278** [comment]
is your problem solve
